import type { GameState } from '../types';

export const G: GameState = {
  screen: 'menu',
  level: 0,
  cap: 4,
  tubes: [],
  start: [],
  par: 1,
  moves: 0,
  history: [],
  selected: -1,
  locked: false,
  anim: null,
  fx: [],
  hintMove: null,
  hintTimer: 0,
  timeMs: 0,
  timing: false,
  lastTick: 0,
  layout: null,
  loopRunning: false,
  motion: true,
  symbols: false,
  shakeI: -1,
  shakeT: 0,
  settleI: -1,
  settleT: 0,
  boardW: 0,
  boardH: 0,
  daily: false,
  hintsLeft: 2,
};
